name: Ubuntu

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: fetchtags
        run: git fetch --unshallow --tags
      - name: submodules
        run: git submodule init && git submodule update
      - name: dependencies
        run: sudo apt update &&
          sudo apt install --assume-yes git libcpprest-dev nlohmann-json3-dev
      - name: make
        run: make